### ISSUE TITLE
Side stands in EDDH

### ISSUE THREAD

**Issue by EisernUnion** [atoff/vatsim-stand-status#10]
Hi, a question where to tweak a setting for this use-case...
In Hamburg the gates at the Terminal are numbered from left to right as: <no>A - <no> - <no>B, e.g. 01A - 01 - 01B
When the most left is used, e.g. 01A the stands 01, 01B are also considered as occupied. This is wrong.... only when 01 (without extension) are used both of the 2 others (01A, 01B are occupied).
When 01A is occupied, only 01 is occupied too, 01B is still useable

![image](https://github.com/atoff/vatsim-stand-status/assets/42810795/0c79ce39-e1f8-4c2a-953d-f9b63fea4977)

**Comment by atoff** [comment]
I don't think this is currently possible - if you don't set `standExtensions` to an empty array, the default behaviour will be to mark all stands with the same root (in this case `01`) as occupied. If you did set it to an empty array, then only the stand (`01A`) would be mark occupied.

This functionality is implemented here: https://github.com/atoff/vatsim-stand-status/blob/master/src/StandStatus.php#L425

It is a private function at the moment unfortunately, which might make it hard to override this behaviour for your use case. I'd welcome a PR that changes it to `protected` or implements a way for this functionality :)
