### ISSUE TITLE
Add Getters and Setters for Longitude / Latitude for gates

### ISSUE THREAD

**Issue by ngoerlitz** [atoff/vatsim-stand-status#8]
Hello,
would it be possible to add getters (and setters) for Latititude/Longitude pairs of a gate? This would be helpful to iterate over the stand list in order to plot gates on a map. 

Thank you in advance.

Kind regards.

**Comment by atoff** [comment]
Getters would be good - not sure what the use case for setters would be for a stand? If you supply the data on init I'm not sure why you'd need to change it

**Comment by atoff** [comment]
See https://github.com/atoff/vatsim-stand-status/pull/9#issuecomment-1013728328
